Inventario/Inventario/Models/AspNetRoles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRoles()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.AspNetUsers1 = new HashSet<AspNetUsers>();
        }
    
        public string Id { get; set; }
        [Required(ErrorMessage = "El nombre es requerido.")]
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers1 { get; set; }
    }
}

Inventario/Inventario/Controllers/AspNetRolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Inventario.Models;

namespace Inventario.Controllers
{
    [Authorize]
    public class AspNetRolesController : Controller
    {
        private InventarioEntities5 db = new InventarioEntities5();

        // GET: AspNetRoles
        public ActionResult Index()
        {
            return View(db.AspNetRoles.ToList());
        }

        // GET: AspNetRoles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                db.AspNetRoles.Add(aspNetRoles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: AspNetRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRoles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: AspNetRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRoles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Inventario/Inventario/Views/AspNetRoles/Create.cshtml
@model Inventario.Models.AspNetRoles

@{
    ViewBag.Title = "Create";
}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>

    ion-icon[name="arrow-back-circle-outline"] {
        font-size: 150%;
    }
</style>

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        <div class="form-horizontal">
        <h4>AspNetRoles</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" id="Create" />
            </div>
        </div>
    </div>
}

<div>

    <a href="@Url.Action("Index", "AspNetRoles")" class="btn btn-info" id="Return">
        <ion-icon name="arrow-back-circle-outline"></ion-icon>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventario/Inventario/Views/AspNetRoles/Delete.cshtml
@model Inventario.Models.AspNetRoles

@{
    ViewBag.Title = "Delete";
}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>
    ion-icon[name="add-circle-outline"] {
        font-size: 300%;
    }

    ion-icon[name="create-outline" ] {
        font-size: 150%;
    }

    ion-icon[name="trash-outline"] {
        font-size: 150%;
    }

    ion-icon[name="eye-outline"] {
        font-size: 150%;
    }
    ion-icon[name="arrow-back-circle-outline"] {
        font-size: 150%;
    }
</style>
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetRoles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" id="Delete"/> |
            <a href="@Url.Action("Index", "AspNetRoles")" class="btn btn-info" id="Return">
                <ion-icon name="arrow-back-circle-outline"></ion-icon>
            </a>
        </div>

    }
</div>

Inventario/Inventario/Views/AspNetRoles/Details.cshtml
@model Inventario.Models.AspNetRoles

@{
    ViewBag.Title = "Details";
}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>
    ion-icon[name="add-circle-outline"] {
        font-size: 300%;
    }

    ion-icon[name="create-outline" ] {
        font-size: 150%;
    }

    ion-icon[name="trash-outline"] {
        font-size: 150%;
    }

    ion-icon[name="eye-outline"] {
        font-size: 150%;
    }

    ion-icon[name="arrow-back-circle-outline"] {
        font-size: 150%;
    }
</style>
<h2>Details</h2>

<div>
    <h4>AspNetRoles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "AspNetRoles", new { id = Model.Id })" class=" btn btn-warning" id="Edit">
        <ion-icon name="create-outline"></ion-icon>
    </a>
    <a href="@Url.Action("Index", "AspNetRoles")" class="btn btn-info" id="Return">
        <ion-icon name="arrow-back-circle-outline"></ion-icon>
    </a>
</p>

Inventario/Inventario/Views/AspNetRoles/Edit.cshtml
@model Inventario.Models.AspNetRoles

@{
    ViewBag.Title = "Edit";
}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>
    ion-icon[name="add-circle-outline"] {
        font-size: 300%;
    }

    ion-icon[name="create-outline" ] {
        font-size: 150%;
    }

    ion-icon[name="trash-outline"] {
        font-size: 150%;
    }

    ion-icon[name="eye-outline"] {
        font-size: 150%;
    }

    ion-icon[name="arrow-back-circle-outline"] {
        font-size: 150%;
    }
</style>
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AspNetRoles</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" id="Edit" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "AspNetRoles")" class="btn btn-info" id="Return">
        <ion-icon name="arrow-back-circle-outline"></ion-icon>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventario/Inventario/Views/AspNetRoles/Index.cshtml
@model IEnumerable<Inventario.Models.AspNetRoles>

@{
    ViewBag.Title = "Index";
}
<br />
<br />
<h2>Roles</h2>

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>
    ion-icon[name="add-circle-outline"] {
        font-size: 300%; 
    }
    ion-icon[name="create-outline" ] {
        font-size: 150%;
    }
    ion-icon[name="trash-outline"]  {
        font-size: 150%;
    }
    ion-icon[name="eye-outline"] {
        font-size: 150%;
    }
</style>
<a href="@Url.Action("Create", "AspNetRoles")" class=" btn btn-success">
    <ion-icon name="add-circle-outline"></ion-icon>
</a>

<br/>
<br/>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a href="@Url.Action("Edit", "AspNetRoles", new { id = item.Id })" class=" btn btn-warning"  id="Edit-@item.Id">
                    <ion-icon name="create-outline"></ion-icon>
                </a> |
                <a href="@Url.Action("Details", "AspNetRoles" , new { id=item.Id })" class="btn btn-primary"  id="Details-@item.Id">
                    <ion-icon name="eye-outline"></ion-icon>
                </a>
                |
                <a href="@Url.Action("Delete", "AspNetRoles", new { id = item.Id })" class="btn btn-danger"  id="Delete-@item.Id">
                    <ion-icon name="trash-outline"></ion-icon>
                </a>

            </td>
</tr>
    }

</table>